//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wosad.Steel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wosad.Steel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A36 (Fy=36ksi),36,58,0,10
        ///A53 Grade B,35,60
        ///A500 Grade B (Fy=42ksi),42,58
        ///A500 Grade B (Fy=46ksi),46,58
        ///A500 Grade C (Fy=46ksi),46,62
        ///A500 Grade C (Fy=50ksi),50,62
        ///A501,36,58
        ///A529 Grade 50,50,65
        ///A529 Grade 55,55,75
        ///A572 Grade 42,42,60
        ///A572 Grade 50,50,65
        ///A572 Grade 55,55,70
        ///A572 Grade 60,60,75
        ///A572 Grade 65,65,80
        ///A618 Grade Iand II,50,70
        ///A618 Grade III,50,65
        ///A913 (Fy=50ksi),50,60
        ///A913 (Fy=60ksi),60,75
        ///A913 (Fy=65ksi),65,80
        ///A913 (Fy=70ksi),70,90
        ///A992,50,65
        ///A242 (Fy=42ksi),42,63
        ///A242 (Fy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AISC360_10_MaterialProperties {
            get {
                return ResourceManager.GetString("AISC360_10_MaterialProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Bolt diameter&gt; &lt;Edge distance&gt;
        ///0.5,0.75
        ///0.625,0.875
        ///0.75,1
        ///0.875,1.125
        ///1,1.25
        ///1.125,1.5
        ///1.25,1.625.
        /// </summary>
        internal static string AISC360_10TableJ3_4_MinimumEdgeDistance {
            get {
                return ResourceManager.GetString("AISC360_10TableJ3_4_MinimumEdgeDistance", resourceCulture);
            }
        }
    }
}
