//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wosad.Wood.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wosad.Wood.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALASKA CEDAR,SelectStructural,None,1150,625,165,525,1000,1400000,510000
        ///ALASKA CEDAR,No1,None,975,525,165,525,900,1300000,470000
        ///ALASKA CEDAR,No2,T2inAndWider,800,425,165,525,750,1200000,440000
        ///ALASKA CEDAR,No3,None,450,250,165,525,425,1100000,400000
        ///ALASKA CEDAR,Stud,T2inAndWider,625,350,165,525,475,1100000,400000
        ///ALASKA CEDAR,Construction,None,900,500,165,525,950,1200000,440000
        ///ALASKA CEDAR,Standard,T2to4,500,275,165,525,775,1100000,400000
        ///ALASKA CEDAR,Utility,None,250,125,165,525,500,1000000,37000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NDS2012_Table4A {
            get {
                return ResourceManager.GetString("NDS2012_Table4A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2&quot;-4&quot; WIDE,DenseSelectStructural,None,3050,1650,175,660,2250,1900000,690000
        ///2&quot;-4&quot; WIDE,SelectStructural,None,2850,1600,175,565,2100,1800000,660000
        ///2&quot;-4&quot; WIDE,NonDenseSelectStructural,None,2650,1350,175,480,1950,1700000,620000
        ///2&quot;-4&quot; WIDE,No1Dense,None,2000,1100,175,660,2000,1800000,660000
        ///2&quot;-4&quot; WIDE,No1,None,1850,1050,175,565,1850,1700000,620000
        ///2&quot;-4&quot; WIDE,No1NonDense,None,1700,900,175,480,1700,1600000,580000
        ///2&quot;-4&quot; WIDE,No2Dense,None,1700,875,175,660,1850,1700000,620000
        ///2&quot;-4&quot; WIDE,No2,None,1500,825,17 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NDS2012_Table4B {
            get {
                return ResourceManager.GetString("NDS2012_Table4B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;&gt;  &lt;&gt;  &lt;&gt;  l_u/d &lt; 7   &lt;&gt;  &lt;7&lt;=l_u/d &lt;=14.3 &gt; &lt;&gt;  &lt;l_u/d &gt;14.3&gt;  &lt;&gt;
        ///&lt;BC&gt;  &lt;Load&gt;  &lt;Bracing&gt;  &lt;N of loads&gt;  &lt;lu_factor&gt;  &lt;dFactor&gt;  &lt;lu_factor&gt; &lt;dFactor&gt;  &lt;lu_factor&gt;  &lt;dFactor&gt;
        ///Cantilever,UniformlyDistributed,Unbraced,1,1.33,0,0.9,3,0.9,3
        ///Cantilever,Concentrated,Unbraced,1,1.87,0,1.44,3,1.44,3
        ///SingleSpan,UniformlyDistributed,Unbraced,1,2.06,0,1.63,3,1.63,3
        ///SingleSpan,Concentrated,Unbraced,1,1.8,0,1.37,3,1.37,3
        ///SingleSpan,Concentrated,Unbraced,2,2.06,0,1.63,3,1.84,0
        ///SingleSpan,Concentrated,BracedAt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NDS2015_Table3_3_3EffectiveLength {
            get {
                return ResourceManager.GetString("NDS2015_Table3_3_3EffectiveLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Grade&gt;&lt;Depth&gt;&lt;Thickness&gt;&lt;Fb&gt;&lt;Ft&gt;&lt;Fc&gt;
        ///Other,4,3,1.5,1.5,1.15
        ///Other,4,4,1.5,1.5,1.15
        ///Other,5,3,1.4,1.4,1.1
        ///Other,5,4,1.4,1.4,1.1
        ///Other,6,3,1.3,1.3,1.1
        ///Other,6,4,1.3,1.3,1.1
        ///Other,8,3,1.2,1.2,1.05
        ///Other,8,4,1.3,1.2,1.05
        ///Other,10,3,1.1,1.1,1
        ///Other,10,4,1.2,1.1,1
        ///Other,12,3,1,1,1
        ///Other,12,4,1.1,1,1
        ///Other,14,3,0.9,0.9,0.9
        ///Other,14,4,1,0.9,0.9
        ///Stud,4,3,1.1,1.1,1.05
        ///Stud,4,4,1.1,1.1,1.05
        ///Stud,5,3,1,1,1
        ///Stud,5,4,1,1,1
        ///Stud,6,3,1,1,1
        ///Stud,6,4,1,1,1
        ///Stud,8,3,1.2,1.2,1.05
        ///Stud,8,4,1.3,1.2,1.05
        ///S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NDS2015_Table4A_SizeFactor {
            get {
                return ResourceManager.GetString("NDS2015_Table4A_SizeFactor", resourceCulture);
            }
        }
    }
}
